### ISSUE TITLE
Authorship

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/javascript#1]
Hey @tbsexton! I just gave you admin rights to this repository. It's yours!

Just to explain a bit: I generated the skeleton with a template of mine, [copier-poetry](https://github.com/pawamoy/copier-poetry), and set you up as the author directly. As a result, the FUNDING file mentions accounts in the name of `tbsexton`. Feel free to change authorship in the project where relevant, or remove this file completely.

Let me know if there's anything you're not comfortable with.

**Comment by tbsexton** [comment]
Ok great, thanks. I probably will remove that file for now. Let me see what kind of plan I can get together, see if any of our team needs to use this in the short-term. I can reach out on gitter, too, if I have any questions. Thanks!
