### ISSUE TITLE
PyPI url points to a different package than this project

### ISSUE THREAD

**Issue by jgarte** [mkdocstrings/javascript#2]
https://github.com/mkdocstrings/javascript/blob/master/README.md#javascript-for-mkdocstrings

https://pypi.org/project/javascript/

**Comment by pawamoy** [comment]
This is fixed, thanks again. Note that the project has no releases on pypi.org yet :slightly_smiling_face:

**Comment by jgarte** [comment]
Thanks! What is the roadmap for releasing on pypi.org?

**Comment by oprypin** [comment]
The repository is just a placeholder right now. There's nothing to release! Also AFAIK, no plans to start work on it.
